### ISSUE TITLE
Xcode compilation errors

### ISSUE THREAD

**Issue by oeresundsgruppen** [huynguyencong/ImageScrollView#43]
/Pods/ImageScrollView/Sources/ImageScrollView.swift:77:28: Type 'UIScrollView.DecelerationRate' (aka 'CGFloat') has no member 'fast'; did you mean 'hash'?

/Pods/ImageScrollView/Sources/ImageScrollView.swift:80:137: 'orientationDidChangeNotification' has been renamed to 'NSNotification.Name.UIDeviceOrientationDidChange'

Can you fix these ( in initialize method ) ?

**Comment by oeresundsgruppen** [comment]
is this library being maintained ??

**Comment by Ahayaki** [comment]
I had the same issue.
I resolved by specifying Swift 4.2 in the build setting.
(Build Settings > “Swift Language Version” > “Swift 4.2”)
Hope it helps.

**Comment by oeresundsgruppen** [comment]
Not sure, I dare change this. Last time bloody XCode suddently showed 1000+ compile errors, due to crappy swift. Apple just needs to make a langauge one time instead of keep changing this. Apple is truely useless.

**Comment by oeresundsgruppen** [comment]
Maybe you can make the library work with 3.0, 4.0 and 4.2 ?

**Comment by oeresundsgruppen** [comment]
Xcode cannot migrate code either, as it is broken as it is. Think I will look for another library, once that is maintained....

**Comment by oeresundsgruppen** [comment]
please remove this one from github, or maintain it!!!!

**Comment by digitsfan** [comment]
I have the same errors and even more... I tried different ways and solved the problems.
I list some of what I did for @oeresundsgruppen : 
1. Cleaned the build  (Command+ Shift + K  or/and clean the contents within /Users/yourusername/Library/Developer/Xcode/DerivedData)
2. Specified the build setting as @Ahayaki mentioned
3. Instead of "Build" the product, "Run" it directly

At last, I appreciate @huynguyencong 's work to keep this pod updated. 
We do not have to reinvent the wheel. Thank you @huynguyencong

**Comment by nvduc2910** [comment]
decelerationRate = UIScrollViewDecelerationRateFast
        NotificationCenter.default.addObserver(self, selector: #selector(ImageScrollView.changeOrientationNotification), name: NSNotification.Name.UIDeviceOrientationDidChange, object: nil)

**Comment by oeresundsgruppen** [comment]
thx, have fixed this once, but would be great if @huynguyencong could update this also.

**Comment by huynguyencong** [comment]
Sorry for late response. I have updated the library for Swift 4.2 a few month ago, so it won't work for older Swift version. It is mentioned in Compatible section.

Please use older version of ImageScrollView (specify it in your Podfile) if you are using older Swift version.

**Comment by JohnHuang1993** [comment]
I had the same issue. There's some error occurred while running the project, I had tried the methods both @Ahayaki @digitsfan mentioned but it doesn't work. How can I fix it?

**Comment by huynguyencong** [comment]
> I had the same issue. There's some error occurred while running the project, I had tried the methods both @Ahayaki @digitsfan mentioned but it doesn't work. How can I fix it?

Which Swift version are you using in your project?

**Comment by JohnHuang1993** [comment]
> > I had the same issue. There's some error occurred while running the project, I had tried the methods both @Ahayaki @digitsfan mentioned but it doesn't work. How can I fix it?
> 
> Which Swift version are you using in your project?

I'm using Swift 4.2 right now.

**Comment by huynguyencong** [comment]
Please check if you have updated the latest version of this library

**Comment by oeresundsgruppen** [comment]
still not fixed in your library

**Comment by huynguyencong** [comment]
What Swift version are you using? Please choose the right version corresponding to your Swift version.
